name: Qodana
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew build
      - name: 'MC Publish'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: nl0Cdq9L
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          curseforge-id: 912202
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-tag: mc1.19.4-0.1.9
          github-generate-changelog: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
